include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

variables:
  JULIA_NUM_THREADS: '4'


# special tests

arm1:
  extends:
    - .julia:1.3
    - .test
  variables:
    GROUP: "Interface"
  tags:
    - aarch64

arm2:
  extends:
    - .julia:1.3
    - .test
  variables:
    GROUP: "Regression"
  tags:
    - aarch64

multithreading:
  extends:
    - .julia:1.3
    - .test
  variables:
    GROUP: "Multithreading"
  tags:
    - 'p6000'

gpu:
  extends:
    - .julia:1.3
    - .test
  variables:
    GROUP: "GPU"
  tags:
    - 'p6000'
  script:
    - julia --project -e 'using Pkg;
                          Pkg.add(\"CuArrays\");
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'
