include: https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml

variables:
  JULIA_NUM_THREADS: 4

.base:
  extends:
    - .julia:1.5
    - .test
  tags:
    - intel

test-arm1:
  extends: .base
  variables:
    GROUP: Interface

test-arm2:
  extends: .base
  variables:
    GROUP: Regression

test-multithreading:
  extends: .base
  variables:
    GROUP: Multithreading

test-GPU:
  extends: .base
  variables:
    GROUP: GPU
  tags:
    - nvidia
    - fastcpu
