name = "OrdinaryDiffEq"
uuid = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "v5.8.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqDiffTools = "01453d9d-ee7c-5054-8395-0335cb756afa"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GenericSVD = "01680d73-4ee2-5a08-a1aa-533608c188bb"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
DiffEqBase = "<= 5.10.3"
DiffEqOperators = ">= 3.2.0"
Parameters = ">= 0.10.0"
ForwardDiff = ">= 0.10.3"
GenericSVD = ">= 0.0.2"
NLsolve = ">= 0.14.1"
RecursiveArrayTools = ">= 0.18.6"
DiffEqDiffTools = ">= 0.4.0"
MuladdMacro = ">= 0.2.1"
StaticArrays = ">= 0.10.3"
DataStructures = ">= 0.15.0"
ExponentialUtilities = ">= 1.2.0"
