[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[sources]
OrdinaryDiffEq = {path = "/home/runner/work/OrdinaryDiffEq.jl/OrdinaryDiffEq.jl"}

[compat]
Documenter = "0.27, 1"
OrdinaryDiffEq = "6"
