[deps]
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
DiffEqDevTools = "2.32"
LSODA = "0.7"
OrdinaryDiffEq = "6.31"
ParameterizedFunctions = "5.15"
Plots = "1.36"
Sundials = "4.10"